### ISSUE TITLE
Fee data amount not checked

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/sygma-solidity#124]
Currently, after the fee data is fetched from fee oracle the amount of tokens can always be set to 0 to pay the minimum (tx cost) amount of tokens instead of the percentage of the total amount.

## Expected Behavior

It should check fee data amount against deposit data amount and fail it if is not the same.

## Current Behavior

It accepts any value as amount.

## Possible Solution

Deposit data is already sent to the `collectFee` and amount from deposit should be compared to fee data amount.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Versions
ChainBridge commit (or docker tag): 
chainbridge-solidity version:
chainbridge-substrate version:
Go version:

**Comment by mpetrun5** [comment]
@nmlinaric @MakMuftic @P1sar Can you please check if I am correct on this one?

**Comment by mpetrun5** [comment]
@lastperson This seems it will also impact decimal discussion as collect fee is done outside of handlers as a separate step which complicates things a bit if the user encodes deposit data amount into 18 decimals.

**Comment by lastperson** [comment]
Guess fee handlers have to be adjusted to also expect 18 decimals.

**Comment by mpetrun5** [comment]
It seems it would be easier to do the conversation in handler instead of user encoding it into 18 decimals as it would require a lot less changes IMO, but we can continue the discussion in slack thread to not pollute this issue.

**Comment by P1sar** [comment]
As we discussed in slack, lets consider next solution:
1. `feeDataDecoded.amount` should not be parsed since there is not much sense in it as maxFee and we want to remove it at all for now. 
2. fee should be calculate a bit different for every dynamic handler `fee = txCost + txCost * _feePercent / 1e4`. Generally we adding fee percent on not of fee cost.
3. tx cost calculation should remain  the same for all handlers
4. `if (fee < txCost) {` this statement is reasonably not needed anymore. 

PS changes should be applied on top of PR https://github.com/sygmaprotocol/sygma-solidity/pull/120
